sudo: required
services:
  - docker

#build the dev version of the client as that is what we are testing here directly
before_install:
  - docker build -t sssuthe/react-test -f ./client/Dockerfile.dev ./client

#run the tests on the dev version of the image
script:
  - docker run -e CI=true sssuthe/react-test npm run test -- --coverage

#now we will build the production images
after_success:
  - docker build -t sssuthe/complex-client ./client
  - docker build -t sssuthe/complex-nginx ./nginx
  - docker build -t sssuthe/complex-server ./server
  - docker build -t sssuthe/complex-worker ./worker
  #first login to the docker cli, these values are in the settings in travis
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #now we need to push these to docker hub
  - docker push sssuthe/complex-client
  - docker push sssuthe/complex-nginx
  - docker push sssuthe/complex-server
  - docker push sssuthe/complex-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: docker-complex
  env: DockerComplex-env
  bucket_name: elasticbeanstalk-us-east-1-033966497385
  bucket_path: docker-complex
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY

